# Generated by Django 3.2.3 on 2021-05-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210522_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('last_school', models.CharField(max_length=255)),
                ('last_position', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('provided_information', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
