# Generated by Django 3.2.3 on 2021-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210529_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='tranparent', max_length=255),
            preserve_default=False,
        ),
    ]
