# Generated by Django 3.2.3 on 2021-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_subject_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='position',
            new_name='last_position',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='workplace',
            new_name='last_workplace',
        ),
        migrations.AddField(
            model_name='teacher',
            name='graduationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
