# Generated by Django 3.2.3 on 2021-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20210618_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
