# Generated by Django 3.2.3 on 2021-07-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_teacher_postal_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher_subject',
            unique_together={('teacher', 'subject')},
        ),
    ]
