# Generated by Django 3.2.3 on 2021-07-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_teacher_year_of_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.language')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'language')},
            },
        ),
    ]
