# Generated by Django 3.2.3 on 2021-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20210723_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
