# Generated by Django 3.2.3 on 2021-08-02 23:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_teacher_is_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[500, 500], upload_to='teachers/profileImages/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='proof_of_address',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[600, 800], upload_to='teachers/addressProof/'),
        ),
    ]
