# Generated by Django 3.2.3 on 2021-05-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210523_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='last_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_school',
            new_name='workplace',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/profileImages/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/addressProof/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
