# Generated by Django 3.2.3 on 2021-05-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_subject_teacher_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessCodes',
            new_name='AccessCode',
        ),
    ]
