# Generated by Django 3.2.3 on 2021-06-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210618_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='graduationDate',
        ),
        migrations.AddField(
            model_name='teacher',
            name='year_of_graduation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
