# Generated by Django 3.2.3 on 2021-07-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_bookmarked_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bookmarked_Teacher',
            new_name='BookmarkedTeacher',
        ),
        migrations.CreateModel(
            name='Teacher_TeachingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher')),
                ('teaching_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teachingfacility')),
            ],
            options={
                'unique_together': {('teacher', 'teaching_facility')},
            },
        ),
    ]
