# Generated by Django 3.2.3 on 2021-07-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20210723_1346'),
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studysession',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teachingfacility'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
