# Generated by Django 3.2.3 on 2021-07-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20210723_1346'),
        ('study_sessions', '0002_auto_20210723_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login.language'),
            preserve_default=False,
        ),
    ]
